### ISSUE TITLE
Home page circuit with project name

### ISSUE THREAD

**Issue by Bobingstern** [UnsignedArduino/LogicalSimulator#208] opened 2022-11-19 17:45 UTC
The home page should have a circuit like this (or something similar) so it doesnt look too empty, I think it would be really neat!
![image](https://user-images.githubusercontent.com/74193405/202864380-d8631c6a-a981-46d1-a33e-e72c98f9793e.png)

`{"version":0,"components":[{"id":"component862","type":11,"x":-25,"y":-25,"angle":4.71238898038469},{"id":"component863","type":13,"x":-25,"y":-150,"angle":4.71238898038469},{"id":"component864","type":9,"x":-25,"y":-300,"angle":4.71238898038469},{"id":"component865","type":2,"x":125,"y":0,"angle":3.141592653589793,"period":6834},{"id":"component866","type":14,"x":275,"y":-25,"angle":4.71238898038469},{"id":"component867","type":11,"x":275,"y":-150,"angle":4.71238898038469},{"id":"component868","type":8,"x":300,"y":-300,"angle":0},{"id":"component869","type":8,"x":450,"y":-275,"angle":1.5707963267948966},{"id":"component870","type":8,"x":450,"y":-25,"angle":3.141592653589793},{"id":"component871","type":12,"x":450,"y":-150,"angle":1.5707963267948966},{"id":"component873","type":8,"x":650,"y":-200,"angle":0},{"id":"component874","type":8,"x":825,"y":-175,"angle":1.5707963267948966},{"id":"component875","type":12,"x":825,"y":-25,"angle":1.5707963267948966},{"id":"component876","type":8,"x":825,"y":150,"angle":1.5707963267948966},{"id":"component877","type":8,"x":650,"y":175,"angle":3.141592653589793},{"id":"component878","type":11,"x":1000,"y":-125,"angle":4.71238898038469},{"id":"component879","type":13,"x":1000,"y":-250,"angle":4.71238898038469},{"id":"component880","type":14,"x":1175,"y":-25,"angle":4.71238898038469},{"id":"component881","type":11,"x":1175,"y":-150,"angle":4.71238898038469},{"id":"component882","type":8,"x":1175,"y":-300,"angle":0},{"id":"component883","type":8,"x":1350,"y":-275,"angle":1.5707963267948966},{"id":"component884","type":8,"x":1350,"y":-25,"angle":3.141592653589793},{"id":"component885","type":14,"x":1525,"y":-100,"angle":4.71238898038469},{"id":"component886","type":11,"x":1525,"y":-225,"angle":4.71238898038469},{"id":"component887","type":8,"x":1550,"y":-325,"angle":0},{"id":"component888","type":8,"x":1700,"y":-300,"angle":1.5707963267948966},{"id":"component889","type":8,"x":1700,"y":-50,"angle":1.5707963267948966},{"id":"component890","type":12,"x":1700,"y":-200,"angle":1.5707963267948966},{"id":"component891","type":11,"x":1875,"y":-50,"angle":4.71238898038469},{"id":"component892","type":13,"x":1875,"y":-175,"angle":4.71238898038469},{"id":"component893","type":9,"x":1875,"y":-325,"angle":4.71238898038469},{"id":"component894","type":2,"x":2012.5,"y":-25,"angle":3.141592653589793,"period":1000},{"id":"component895","type":2,"x":1000,"y":-25,"angle":4.71238898038469,"period":3653},{"id":"component896","type":3,"x":1006.25,"y":-368.75,"angle":0},{"id":"component897","type":2,"x":375,"y":0,"angle":3.141592653589793,"period":1500},{"id":"component898","type":2,"x":1275,"y":-12.5,"angle":4.71238898038469,"period":9043},{"id":"component899","type":2,"x":1531.25,"y":0,"angle":4.71238898038469,"period":1500},{"id":"component900","type":8,"x":1600,"y":-175,"angle":3.141592653589793},{"id":"component902","type":2,"x":637.5,"y":0,"angle":4.71238898038469,"period":2023}],"connections":[{"fromComponentID":"component865","fromComponentPointIndex":0,"toComponentID":"component862","toComponentPointIndex":1},{"fromComponentID":"component862","fromComponentPointIndex":2,"toComponentID":"component863","toComponentPointIndex":1},{"fromComponentID":"component863","fromComponentPointIndex":2,"toComponentID":"component864","toComponentPointIndex":1},{"fromComponentID":"component864","fromComponentPointIndex":2,"toComponentID":"component862","toComponentPointIndex":0},{"fromComponentID":"component865","fromComponentPointIndex":0,"toComponentID":"component864","toComponentPointIndex":0},{"fromComponentID":"component870","fromComponentPointIndex":1,"toComponentID":"component866","toComponentPointIndex":1},{"fromComponentID":"component866","fromComponentPointIndex":2,"toComponentID":"component867","toComponentPointIndex":1},{"fromComponentID":"component867","fromComponentPointIndex":2,"toComponentID":"component868","toComponentPointIndex":0},{"fromComponentID":"component868","fromComponentPointIndex":1,"toComponentID":"component869","toComponentPointIndex":0},{"fromComponentID":"component870","fromComponentPointIndex":1,"toComponentID":"component866","toComponentPointIndex":0},{"fromComponentID":"component869","fromComponentPointIndex":1,"toComponentID":"component871","toComponentPointIndex":0},{"fromComponentID":"component871","fromComponentPointIndex":2,"toComponentID":"component870","toComponentPointIndex":0},{"fromComponentID":"component873","fromComponentPointIndex":1,"toComponentID":"component874","toComponentPointIndex":0},{"fromComponentID":"component874","fromComponentPointIndex":1,"toComponentID":"component875","toComponentPointIndex":0},{"fromComponentID":"component875","fromComponentPointIndex":2,"toComponentID":"component876","toComponentPointIndex":0},{"fromComponentID":"component876","fromComponentPointIndex":1,"toComponentID":"component877","toComponentPointIndex":0},{"fromComponentID":"component878","fromComponentPointIndex":2,"toComponentID":"component879","toComponentPointIndex":1},{"fromComponentID":"component884","fromComponentPointIndex":1,"toComponentID":"component880","toComponentPointIndex":1},{"fromComponentID":"component880","fromComponentPointIndex":2,"toComponentID":"component881","toComponentPointIndex":1},{"fromComponentID":"component881","fromComponentPointIndex":2,"toComponentID":"component882","toComponentPointIndex":0},{"fromComponentID":"component882","fromComponentPointIndex":1,"toComponentID":"component883","toComponentPointIndex":0},{"fromComponentID":"component884","fromComponentPointIndex":1,"toComponentID":"component880","toComponentPointIndex":0},{"fromComponentID":"component885","fromComponentPointIndex":2,"toComponentID":"component886","toComponentPointIndex":1},{"fromComponentID":"component886","fromComponentPointIndex":2,"toComponentID":"component887","toComponentPointIndex":0},{"fromComponentID":"component887","fromComponentPointIndex":1,"toComponentID":"component888","toComponentPointIndex":0},{"fromComponentID":"component888","fromComponentPointIndex":1,"toComponentID":"component890","toComponentPointIndex":0},{"fromComponentID":"component890","fromComponentPointIndex":2,"toComponentID":"component889","toComponentPointIndex":0},{"fromComponentID":"component894","fromComponentPointIndex":0,"toComponentID":"component891","toComponentPointIndex":1},{"fromComponentID":"component891","fromComponentPointIndex":2,"toComponentID":"component892","toComponentPointIndex":1},{"fromComponentID":"component892","fromComponentPointIndex":2,"toComponentID":"component893","toComponentPointIndex":1},{"fromComponentID":"component893","fromComponentPointIndex":2,"toComponentID":"component891","toComponentPointIndex":0},{"fromComponentID":"component894","fromComponentPointIndex":0,"toComponentID":"component893","toComponentPointIndex":0},{"fromComponentID":"component895","fromComponentPointIndex":0,"toComponentID":"component878","toComponentPointIndex":1},{"fromComponentID":"component895","fromComponentPointIndex":0,"toComponentID":"component878","toComponentPointIndex":0},{"fromComponentID":"component897","fromComponentPointIndex":0,"toComponentID":"component867","toComponentPointIndex":0},{"fromComponentID":"component898","fromComponentPointIndex":0,"toComponentID":"component884","toComponentPointIndex":0},{"fromComponentID":"component898","fromComponentPointIndex":0,"toComponentID":"component881","toComponentPointIndex":0},{"fromComponentID":"component899","fromComponentPointIndex":0,"toComponentID":"component885","toComponentPointIndex":0},{"fromComponentID":"component899","fromComponentPointIndex":0,"toComponentID":"component885","toComponentPointIndex":1},{"fromComponentID":"component890","fromComponentPointIndex":2,"toComponentID":"component900","toComponentPointIndex":0},{"fromComponentID":"component899","fromComponentPointIndex":0,"toComponentID":"component886","toComponentPointIndex":0},{"fromComponentID":"component902","fromComponentPointIndex":0,"toComponentID":"component873","toComponentPointIndex":0},{"fromComponentID":"component902","fromComponentPointIndex":0,"toComponentID":"component875","toComponentPointIndex":1}]}`

**Comment by UnsignedArduino** [comment] 2022-11-19 19:14
Yes, as documented in the SEO issue (https://github.com/UnsignedArduino/LogicalSimulator/issues/36) we want to fill the main page up with more content. I'm considering taking your four bit adder example and using it for the big image.

**Comment by UnsignedArduino** [comment] 2022-11-19 19:19
Duplicate of https://github.com/UnsignedArduino/LogicalSimulator/issues/36

**Closed** 2022-11-19 19:18 UTC
Labels: duplicate
