### ISSUE TITLE
Cached Chunk Update (CCU) optimisation details and redundancy

### ISSUE THREAD

**Issue by Bobingstern** [UnsignedArduino/LogicalSimulator#209] opened 2022-11-19 19:16 UTC
Firstly, determine the number of components in each chunk. Initialise a stack of all the current components and choose one. Find all connected components and connection of connected components until we hit the chunk size. Next, collapse these components into a "ghost IC" and run the truth table analysis algorithm from issue #206 (I will abbreviate will ICTTA (IC truth table analysis) ) This is the bulk of it but we must remember and be very careful of propagation delays and make sure that the amount of frames to propagate the output is the same. The issue now is the _animation_ of propagation. It is impossible to truly animate correctly without having to propagate each state. For now, we will make this only accessible for advanced users where each chunk will be rendered as an IC of the size of the chunk. If this is what we do, we must make sure that components inside a chunk are not too far away. There should be an option in the menu that ask the user if they want to enable CCU optimisation and only will this happen. The only reason that this would be useful is for large circuit projects where some sections are not even powered for a significant amount of time. Storing truth tables will reduce _new_ user friendliness but will make developing large circuits much faster although if in large circuits there are a lot of ICs, ICTTA will do the trick. 

This leads to crossroads: Implement CCU but lose _new_ user friendliness or simply use ICTTA.

By nature of design CCU _is_ ICTTA but scaled up largely but without component animations. A very unrealistic approach would be to also store the power states of each of components _inside_ the chunks to animate but this defeats the purpose of speed as doing table lookups may even be slower. I leave this up to you for a second opinion but I believe CCU, although it will increase speed, will defeat the main purpose of the simulator: To animate the propagation and simulation of logic gates. I think for now, ICTTA will be the best optimisation.

**Comment by UnsignedArduino** [comment] 2022-11-19 19:21
I think IC truth table analysis will be better. If you are repeating components, you should probably be using ICs. I'll consider adding a button to hide all components connected to an IC definition.

**Comment by Bobingstern** [comment] 2022-11-19 19:27
Sounds good to me, although there should still be some sort of way to alert the user if they are copy and pasting the same set of components multiple times or have a bunch of duplicates of the same set of components to use an IC. ICTTA for the win!

**Comment by UnsignedArduino** [comment] 2022-11-19 19:32
Then this is a duplicate of https://github.com/UnsignedArduino/LogicalSimulator/issues/206

**Closed** 2022-11-19 19:31 UTC
Labels: duplicate
